name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # 👈 Required to retrieve git history

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          install-command: yarn install --immutable

      - name: Use NextJS build cache
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          key: nextjs-v1-${{ hashFiles('**/yarn.lock') }}

      - name: Build
        env:
          NODE_ENV: production
          IGDB_CLIENT_ID: ${{ secrets.IGDB_CLIENT_ID }}
          IGDB_SECRET: ${{ secrets.IGDB_SECRET }}
          REDIS_URL: ${{ secrets.REDIS_URL }}
        run: yarn build

      - name: Lint
        run: yarn lint

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          exitZeroOnChanges: true
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_TOKEN }}
