name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          install-command: yarn install --immutable

      - name: Use NextJS build cache
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          key: nextjs-v1-${{ hashFiles('**/yarn.lock') }}

      - name: Build
        env:
          NODE_ENV: production
          IGDB_CLIENT_ID: ${{ secrets.IGDB_CLIENT_ID }}
          IGDB_SECRET: ${{ secrets.IGDB_SECRET }}
        run: yarn build
#  lint:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Check out Git repository
#        uses: actions/checkout@v1
#
#      - name: Setup Node
#        uses: actions/setup-node@v1
#        with:
#          node-version: 14
#
#      - name: Install dependencies
#        uses: bahmutov/npm-install@v1
#        with:
#          install-command: yarn install --immutable
#
#      - name: Lint
#        run: yarn lint

#  test:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Check out Git repository
#        uses: actions/checkout@v1
#
#      - name: Setup Node
#        uses: actions/setup-node@v1
#        with:
#          node-version: 14
#
#      - name: Install dependencies
#        uses: bahmutov/npm-install@v1
#        with:
#          install-command: yarn install --immutable
#
#      - name: Test
#        env:
#          NODE_ENV: test
#        run: yarn test
